# Generated by Django 6.0 on 2025-12-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="catagory",
            new_name="category",
        ),
    ]
