# Generated by Django 6.0 on 2026-01-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_catagory_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(upload_to="products/main/"),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sizes",
                to="main.product",
            ),
        ),
    ]
