# Generated by Django 6.0 on 2026-01-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="updated_ad",
            new_name="updated_at",
        ),
    ]
