# Generated by Django 6.0 on 2026-01-21 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("brand", models.CharField(max_length=100, verbose_name="Бренд")),
                (
                    "image",
                    models.ImageField(upload_to="devices/", verbose_name="Изображение"),
                ),
                (
                    "screen_size",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Диагональ экрана",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Встроенная память",
                    ),
                ),
                (
                    "battery",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Аккумулятор"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Операционная система",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "specifications",
                    models.TextField(default="{}", verbose_name="Доп. характеристики"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comparison.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ключ сессии",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        to="comparison.device", verbose_name="Товары"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение",
                "verbose_name_plural": "Сравнения",
            },
        ),
    ]
