# Generated by Django 6.0 on 2026-01-21 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparison", "0001_initial"),
        ("main", "0003_alter_product_main_image_alter_productsize_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comparison",
            unique_together={("user", "session_key")},
        ),
        migrations.AddField(
            model_name="comparison",
            name="products",
            field=models.ManyToManyField(related_name="comparisons", to="main.product"),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("brand", models.CharField(max_length=100, verbose_name="Бренд")),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Изображение"
                    ),
                ),
                (
                    "screen_size",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Диагональ экрана",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Встроенная память",
                    ),
                ),
                (
                    "battery",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Аккумулятор"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Операционная система",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "specifications",
                    models.TextField(default="{}", verbose_name="Доп. характеристики"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comparison.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.RemoveField(
            model_name="comparison",
            name="devices",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
